language: go

install:
    - go get golang.org/x/tools/imports/...
    - wget -qO- https://github.com/golangci/golangci-lint/releases/download/v1.3.7/golangci-lint-1.3.7-linux-amd64.tar.gz | tar xvz --strip 1 golangci-lint-1.3.7-linux-amd64/golangci-lint

script:
    - GOVERSION=$(go version | awk '{ print $3 }')
    - test $GOVERSION = "devel" || ./golangci-lint run -v ./...
    - go test -v ./...

go:
    - 1.9.x
    - 1.10.x
    - 1.11.x
    - 1.12.x
    - tip
